### PR TITLE
Object oriented Javascript

### PR DESCRIPTION
**Pull request by cundd**
I tried to transform the Javascript into OOP style. The benefits are a clearer separation of the code's aspects and structure. 

Another big point is the ability to access the Javascript object through `$('#map').data('gomapsextcontroller')`, which allows external extensions to modify the map (e.g. focus a marker, change the selected categories).

### CODE REVIEW

**Comment by mhirdes** [comment]
Hey, sry, that I answer now. I was a little bit busy. First of all, thanks for your work. Looks very good. I think everything should work like before?

**Comment by cundd** [comment]
I tried to make everything work as it did before. But we didn't use all of the features of your extension in our use cases. 
And one thing that may need a bit of work is, to get your latest changes back into the system.

**Comment by mhirdes** [comment]
Which changes do you mean? There were no changes the last 24 days.

**Comment by cundd** [comment]
Ah ok... I thought because github says: "This branch has conflicts that must be resolved"

**Comment by mhirdes** [comment]
Please check https://github.com/mhirdes/go_maps_ext/tree/iresults-feature/oop-javascript I had problems with the checkbox selection by categories. To throw an error I deleted, because the length of the array could be zero. And I deleted the string type check, because the selection didn't work. Maybe you can take a look into the branch. If you aggree I would merge the branche with the master.

**Comment by cundd** [comment]
I guess that it's good. Unfortunately the project where I could have tested it is already live. Maybe I could give you more feedback the next time we need it...

**Pull request merged**
