### PR TITLE
Reformat code to PSR2 and optimize it

### PR DESCRIPTION
**Pull request by simonschaufi**
* use 'use' statement
* use int instead of integer
* adjust docheader where needed
* close html tag in fluid templates
* use new way of including fluid namespaces
* use f:comment instead of HideInFrontendViewHelper
* use correct forge URL in composer.json
* cleanup ext_emconf config

### CODE REVIEW

**Comment by simonschaufi** [comment]
can this be merged please?

**Comment by simonschaufi** [comment]
@mhirdes can this be merged please?

**Comment by simonschaufi** [comment]
@mhirdes can this be merged?

**Comment by mhirdes** [comment]
Thanks a lot for your work

**Pull request merged**
